import { jsPDF } from "jspdf";

export const exportSoilReportPDF = (reportData) => {
  const doc = new jsPDF();
  const { site, soil, kaegroSoil, zone, earthquakeRecs, cost } = reportData;
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let y = 20;

  // Title
  doc.setFontSize(20);
  doc.setTextColor(40, 40, 40);
  doc.text("Site Analysis & Cost Estimation Report", margin, y);
  y += 10;
  
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated by doonITes Sweet Home Planner | ${new Date().toLocaleDateString()}`, margin, y);
  y += 15;

  // 1. Site Location
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text("1. Site Location", margin, y);
  y += 8;
  
  doc.setFontSize(11);
  doc.setTextColor(60, 60, 60);
  doc.text(`Latitude: ${site.lat}`, margin, y); y += 6;
  doc.text(`Longitude: ${site.lng}`, margin, y); y += 6;
  doc.text(`Seismic Zone: ${zone}`, margin, y); y += 12;

  // 2. Soil Analysis (Local)
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text("2. Soil Analysis (Local Database)", margin, y);
  y += 8;

  doc.setFontSize(11);
  doc.setTextColor(60, 60, 60);
  doc.text(`Soil Type: ${soil.type}`, margin, y); y += 6;
  doc.text(`Bearing Capacity: ${soil.bearingCapacity} kN/m²`, margin, y); y += 6;
  doc.text(`Recommended Foundation: ${soil.foundationType}`, margin, y); y += 6;
  
  // Risk Level with color indication text
  const riskColor = soil.riskLevel === 'High' ? [239, 68, 68] : [16, 185, 129];
  doc.setTextColor(...riskColor);
  doc.text(`Risk Level: ${soil.riskLevel}`, margin, y); 
  doc.setTextColor(60, 60, 60); // Reset
  y += 12;

  // 3. Live Soil Data (Kaegro)
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text("3. Live Soil Data (Kaegro API)", margin, y);
  y += 8;

  doc.setFontSize(11);
  doc.setTextColor(60, 60, 60);
  
  if (kaegroSoil) {
    Object.entries(kaegroSoil).forEach(([key, value]) => {
       // Format key: camelCase/snake_case to Title Case
       const formattedKey = key
          .replace(/([A-Z])/g, ' $1') // insert space before capital letters
          .replace(/_/g, ' ') // replace underscores with spaces
          .replace(/^\w/, c => c.toUpperCase()); // capitalize first letter

       const displayValue = typeof value === 'object' && value !== null 
          ? JSON.stringify(value) // Keep nested objects as string if any
          : String(value);

       doc.text(`${formattedKey}: ${displayValue}`, margin, y);
       y += 6;
    });
    y += 4; // Extra spacing after list
  } else {
    doc.text("Data not available or API error.", margin, y);
    y += 10;
  }

  // Check if we need a new page
  if (y > 250) {
    doc.addPage();
    y = 20;
  }

  // 4. Compliance
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text("4. Compliance & Safety (Earthquake Recs)", margin, y);
  y += 8;

  doc.setFontSize(11);
  doc.setTextColor(60, 60, 60);
  earthquakeRecs.forEach(rec => {
      const splitRec = doc.splitTextToSize(`• ${rec}`, pageWidth - (margin * 2));
      doc.text(splitRec, margin, y);
      y += (splitRec.length * 6) + 2;
  });
  y += 10;

  // Check page again
  if (y > 240) {
    doc.addPage();
    y = 20;
  }

  // 5. Cost Estimation
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text("5. Cost Estimation", margin, y);
  y += 8;

  doc.setFontSize(11);
  doc.setTextColor(60, 60, 60);
  doc.text(`Total Built-Up Area: ${cost.totalArea} sq.ft`, margin, y); y += 6;
  
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text(`Estimated Total Cost: ₹${cost.estimatedCost.toLocaleString()}`, margin, y); 
  y += 10;

  doc.setFontSize(11);
  doc.setTextColor(60, 60, 60);
  doc.text("Breakdown:", margin, y); y += 6;
  doc.text(`• Structure: ₹${cost.breakdown.structure.toLocaleString()}`, margin + 5, y); y += 6;
  doc.text(`• Finishes: ₹${cost.breakdown.finishes.toLocaleString()}`, margin + 5, y); y += 6;
  doc.text(`• Electrical: ₹${cost.breakdown.electrical.toLocaleString()}`, margin + 5, y); y += 6;
  doc.text(`• Plumbing: ₹${cost.breakdown.plumbing.toLocaleString()}`, margin + 5, y); y += 6;
  doc.text(`• Misc/Labor: ₹${cost.breakdown.misc.toLocaleString()}`, margin + 5, y); y += 15;

  // Footer / Disclaimer
  doc.setFontSize(9);
  doc.setTextColor(150, 150, 150);
  doc.text("Disclaimer: This is an automated estimate generated by software. Please consult a professional architect or structural engineer for accurate planning and costing.", margin, 280);

  doc.save("site_analysis_report.pdf");
};